Update git-e-github.md
glaucia86/frontend-bootcamp-online pull request #5
Opened 2019-09-11 00:47 UTC by TiagoBehenck

Adicionando [arquivo](https://github.com/TiagoBehenck/frontend-bootcamp-online/blob/master/fase-1/fase-1.4-git-github/git-e-github.md) ```.md``` na pasta ```Git``` e ```GitHub``` com descrição de como cada um funciona, explicado cada um deles. 

- [x]  Commit
- [x]  Pull
- [x] Branches

2019-09-13 13:53 UTC, marcjal requested changes

2019-09-13 13:53 UTC, marcjal commented on fase-1/fase-1.4-git-github/git-e-github.md
> +Se trata de um sistema de controle de versionamento para o seu código. Por meio dele é possível desenvolver projetos em que diversos desenvolvedores podem contribuir simultaneamente, editando, criand
Tem um problema de escrita `altarações` troca por `alterações`.

2019-09-13 13:54 UTC, marcjal commented on fase-1/fase-1.4-git-github/git-e-github.md
> +Se trata de um sistema de controle de versionamento para o seu código. Por meio dele é possível desenvolver projetos em que diversos desenvolvedores podem contribuir simultaneamente, editando, criand
Good Job

2019-09-13 13:55 UTC, marcjal requested changes
Tem um problema de escrita `altarações` troca por `alterações`.

2019-09-13 13:57 UTC, TiagoBehenck commented on fase-1/fase-1.4-git-github/git-e-github.md
> +Se trata de um sistema de controle de versionamento para o seu código. Por meio dele é possível desenvolver projetos em que diversos desenvolvedores podem contribuir simultaneamente, editando, criand
Opa, valeu!

2019-09-13 18:12 UTC, marcjal approved these changes

2019-09-13 18:13 UTC, marcjal commented on fase-1/fase-1.4-git-github/git-e-github.md
> +Se trata de um sistema de controle de versionamento para o seu código. Por meio dele é possível desenvolver projetos em que diversos desenvolvedores podem contribuir simultaneamente, editando, criand
Approved

2019-09-14 16:39 UTC, glaucia86 approved these changes
LGTM 👍 

Gente! É isso aí. Ficou excelente!

Muito obrigada pela contribuição de vocês!

cc: @TiagoBehenck

2019-09-14 16:40 UTC, merged

2019-09-14 16:40 UTC, glaucia86 commented
Muito obrigada pela contribuição de vocês!

cc: @TiagoBehenck @marcjal 

![bitmoji](https://render.bitstrips.com/v2/cpanel/430025ee-b231-4e76-b651-9909984b7b68-51d9afb6-b666-4b20-ac39-494c4b2f62a7-v1.png?transparent=1&palette=1&width=246)